# NumPy

In [1]:
# Imports
import numpy as np

## NumPy arrays

In [2]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
my_matrix = [[1,2,3],[4,5,6]]
my_matrix

[[1, 2, 3], [4, 5, 6]]

In [5]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6]])

## Build-in Methods

### arange 

In [6]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

### zeros and ones

In [7]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [8]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
np.ones(5)

array([1., 1., 1., 1., 1.])

### linspace

In [10]:
np.linspace(0,10,15)

array([ 0.        ,  0.71428571,  1.42857143,  2.14285714,  2.85714286,
        3.57142857,  4.28571429,  5.        ,  5.71428571,  6.42857143,
        7.14285714,  7.85714286,  8.57142857,  9.28571429, 10.        ])

### eye

In [11]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random

### rand 

Create an array with an shape an population from [0,1]

In [12]:
np.random.rand(2)

array([0.38783056, 0.59072517])

In [13]:
np.random.rand(2,2)

array([[0.09146317, 0.44671794],
       [0.13875196, 0.62472409]])

### randn

Return an array with "normal" distribution.

In [14]:
np.random.randint(1,100,3)

array([ 6, 96, 39])

### randint

Return random integers from `low` (inclusive) to `high` (exclusive).

In [15]:
np.random.randint(1,100,10)

array([20, 51, 64, 73, 79, 37, 82, 25, 52, 11])

## Array attributes and Methods

In [16]:
array_ = np.arange(20)
rand_array = np.random.randint(0,50,10)
print(array_)
print(rand_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[34 22 38  2  4 14 23 31 36 13]


### Reshape

In [17]:
array_.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

### max,min,argmax,argmin

In [18]:
np.random.seed(123)
rand_array

array([34, 22, 38,  2,  4, 14, 23, 31, 36, 13])

In [19]:
rand_array.min()

2

In [20]:
rand_array.max()

38

## Type

In [21]:
array_.dtype

dtype('int64')

## Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. I recommend usually using the comma notation for clarity.

In [22]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [23]:
#Indexing row
arr_2d[1]

array([20, 25, 30])

In [24]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
arr_2d[1][0]

20

In [25]:
# Getting individual element value
arr_2d[1,0]

20

In [26]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [27]:
#Shape bottom row
arr_2d[2]

array([35, 40, 45])

In [28]:
#Shape bottom row
arr_2d[2,:]

array([35, 40, 45])