# NumPy

In [2]:
# Imports
import numpy as np

## NumPy arrays

In [20]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [21]:
np.array(my_list)

array([1, 2, 3])

In [22]:
my_matrix = [[1,2,3],[4,5,6]]
my_matrix

[[1, 2, 3], [4, 5, 6]]

In [27]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6]])

## Build-in Methods

### arange 

In [32]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

### zeros and ones

In [34]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [38]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [39]:
np.ones(5)

array([1., 1., 1., 1., 1.])

### linspace

In [44]:
np.linspace(0,10,15)

array([ 0.        ,  0.71428571,  1.42857143,  2.14285714,  2.85714286,
        3.57142857,  4.28571429,  5.        ,  5.71428571,  6.42857143,
        7.14285714,  7.85714286,  8.57142857,  9.28571429, 10.        ])

### eye

In [46]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random

### rand 

Create an array with an shape an population from [0,1]

In [56]:
np.random.rand(2)

array([0.84943179, 0.72445532])

In [57]:
np.random.rand(2,2)

array([[0.61102351, 0.72244338],
       [0.32295891, 0.36178866]])

### randn

Return an array with "normal" distribution.

In [51]:
np.random.randint(1,100,3)

array([98, 97, 48])

### randint

Return random integers from `low` (inclusive) to `high` (exclusive).

In [58]:
np.random.randint(1,100,10)

array([28, 35, 98, 77, 41,  4, 70, 65, 76, 35])

## Array attributes and Methods

In [61]:
array_ = np.arange(20)
rand_array = np.random.randint(0,50,10)
print(array_)
print(rand_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 6 45 26 16  6 14 39 11  7  1]


### Reshape

In [63]:
array_.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

### max,min,argmax,argmin

In [70]:
np.random.seed(123)
rand_array

array([ 6, 45, 26, 16,  6, 14, 39, 11,  7,  1])

In [71]:
rand_array.min()

1

In [73]:
rand_array.max()

45

## Type

In [76]:
array_.dtype

dtype('int64')